### ISSUE TITLE
Add support of Unity 2020.1.x

### ISSUE THREAD

**Issue by lvgrecords** [Bullrich/UnityFolderCleaner#1]
Current implementation is not working properly on Unity 2020.1.x (in my case Unity 2020.1.17f1).

`AssetDatabase.Refresh();` cause next warning

```
A meta data file (.meta) exists but its folder 'Assets/Plugins/DOTween' can't be found, and has been created. Empty directories cannot be stored in version control, so it's assumed that the meta data file is for an empty directory in version control. When moving or deleting folders outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
UnityEditor.AssetDatabase:Refresh()
```

**Comment by Bullrich** [comment]
FYI, this happened because the system was not deleting the root folder metafile. 

While this was throwing a warning, it was immediately cleaned by Unity after the `AssetDatabase:Refresh`.

Thanks for making the issue and the PR to fix it!
